@startuml

title High Level Architecture of Entitlement Deliverables\n\n\n

scale 750 width
skinparam component {
	BackgroundColor LightSteelBlue
	BorderColor Black
}

skinparam database {
	BackgroundColor DodgerBlue
	BorderColor Black
}

skinparam node {
	BackgroundColor SkyBlue
	BorderColor Black
}

left to right direction

component [UI Component] as uiClient
component [Workflow Service] as workflowms


rectangle "Identity Repositories"{
database opendj [LDAP \n(OpenDJ)
]
database companyAD [company\nGlue\n(AD LDAP)
]
database oracleExt [Target\nDatabase\n(Oracle)
]

}

database mongoDB [Mongo\nDatastore
]


rectangle "Identity Management"{
node openidm [OpenIDM
]
database oracleInt [Internal\nDatabase\n(Oracle)
]
}

rectangle "Access Management"{
node openam [OpenAM
]
}



workflowms --> openidm
workflowms <-- openidm

workflowms --> mongoDB

openidm --> opendj
openidm --> oracleInt
openidm --> oracleExt
openam --> opendj
openam --> companyAD

uiClient --> workflowms
uiClient <-- workflowms
uiClient --> mongoDB


@enduml
