@startuml

skinparam componentStyle uml2

skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

skinparam database {
	BackgroundColor DodgerBlue
	BorderColor Black
}

title Microservice Platform Architecture

node "Securities Frontend" {
  [securities-poc-fe]
}

node "Securities Portfolio" {
  [securities-poc-portfolio]
}

node "Securities Watchlist" {
  [securities-poc-watchlist]
}

node "Securities Foreign Exchange" {
  [securities-poc-fx]
}

node "Securities Alerts" {
  [securities-poc-alerts]
}




node "Securities Service" {
  [securities-poc-fe] - [securities-poc-services] : REST-HTTP
  '[services-api] <-- [securities-poc-services] : implementation
  [securities-poc-services] -- [securities-poc-portfolio]  : REST-HTTP
  [securities-poc-services] -- [securities-poc-watchlist]  : REST-HTTP
  [securities-poc-services] -- [securities-poc-fx]  : REST-HTTP
  [securities-poc-services] -- [securities-poc-alerts]  : REST-HTTP
}


database securitiesPocGatewayDatabase [Subscriptions\nDatabase
]

node "Securities Gateway" {
  [securities-poc-gw]
  [securities-poc-gw] --> securitiesPocGatewayDatabase
  [securities-poc-portfolio] -- [securities-poc-gw]  : MESSAGING
  [securities-poc-watchlist] -- [securities-poc-gw]  : MESSAGING
  [securities-poc-fx] -- [securities-poc-gw]  : MESSAGING
  [securities-poc-alerts] -- [securities-poc-gw]  : MESSAGING
}


@enduml
